version: '3'
services:
  agent:
    network_mode: "host"
    build:
      context: .
      dockerfile: /agent/Dockerfile
    depends_on:
      - producer
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    ports:
      - "162:162/udp"
#     networks:
#       - broker-kafka
# networks:
#   broker-kafka:
#     driver: bridge