version: '3'
services:
  receptor:
    build:
      context: .
      dockerfile: receptor/Dockerfile
    ports:
      - "162:162/udp"
    networks:
      backend:
        ipv4_address: 172.16.239.20
  agente:
    image: elcolio/net-snmp
    # ports:
    #   - "162:162/udp"
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24